name: Checkstyle

on:
    push:
        branches:
            - main
            - develop

    pull_request:
        branches:
            - main
            - develop

jobs:
    checkstyle:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: maven

            - name: Run Checkstyle
              run: mvn -B checkstyle:check --file pom.xml
